---
image: vaultwarden
version: v0.5.60
name: vaultwarden
description: "[Vaultwarden](https://github.com/dani-garcia/vaultwarden) Unofficial Bitwarden compatible server written in Rust, formerly known as bitwarden_rs."
ext_release: "1.37.4-alpine@sha256:19ea2b669945d842dadc3d500f2d6a795866a003330f59a47b9634658bae98bb"
arch:
  - aarch64
  - x86_64
  - armv7
