#!/usr/bin/with-contenv bash
# shellcheck shell=bash

declare admin_token
declare secret_key

# Set a random secret, to remove confusing warning from logs.
secret_key=$(openssl rand -base64 32)
export ROCKET_SECRET_KEY="${secret_key}"

# Show admin token in the log, if config does not exist.
if [ ! -f '/app/vw/data/config.json' ]; then
    admin_token=$(openssl rand -base64 48)
    export ADMIN_TOKEN="${admin_token}"

    echo
    echo
    echo "READ THIS CAREFULLY! READ THIS CAREFULLY!"
    echo
    echo
    echo "This is your temporary random admin token/password!"
    echo
    echo "${admin_token}"
    echo
    echo "Be sure to change it in the admin panel, as soon as possible."
    echo
    echo "After you have changed ANY setting in the admin panel,"
    echo "the add-on will NOT generate a new token on each start"
    echo "and stops showing this message."
    echo
fi

exec \
    s6-notifyoncheck -d -n 300 -w 1000 \
        cd /app/vw s6-setuidgid abc /app/vw/vaultwarden
