name: Build Image

on:
  release:
    types: [published]
  push:

jobs:
  build-and-deploy:
    name: Build and deploy
    uses: chukysoria/workflows/.github/workflows/build-image.yml@e1e702f1203019373b58d387d98f56883db43607 # v1.1.40
