name: Build Image

on:
  release:
    types: [published]
  push:

jobs:
  build-and-deploy:
    name: Build and deploy
    uses: chukysoria/workflows/.github/workflows/build-image.yml@63ded7f0727ba0cff982f47f2f03b1f0f7f44be1 # v1.1.41
