name: Permission check
on:
  pull_request_target:
    paths:
      - '**/run'
      - '**/finish'
      - '**/check'
jobs:
  permission_check:
    uses: chukysoria/workflows/.github/workflows/init-svc-executable-permissions.yml@9b1c843ea56815ffcc5b0e975cc1dac811fef922 # v1.1.39
